### ISSUE TITLE
Python Compatibility Errors 

### ISSUE THREAD

**Issue by ghostaccount737** [strawlab/pyopy#16]
Upon Running

` hctsa-cli install --engine matlab --force-download --generate-bindings` 

It gives me the following log
 
```
Traceback (most recent call last):
  File "/usr/local/bin/hctsa-cli", line 11, in <module>
    load_entry_point('pyopy==0.1.0', 'console_scripts', 'hctsa-cli')()
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 480, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 2691, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 2322, in load
    return self.resolve()
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 2328, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.5/dist-packages/pyopy/hctsa/hctsa_cli.py", line 5, in <module>
    from pyopy.hctsa.hctsa_bindings_gen import gen_bindings
  File "/usr/local/lib/python3.5/dist-packages/pyopy/hctsa/hctsa_bindings_gen.py", line 298
    exec '\n'.join(binding_imports) in globals()  # We are using nasty execs around that need these imports
            ^
SyntaxError: invalid syntax


```

**Comment by ghostaccount737** [comment]
I can run it with `python2.7` and I am closing this issue for now

![summary](https://user-images.githubusercontent.com/44138475/76254626-d0607e80-6272-11ea-8b8c-64c908c7f75a.png)
